# Generated by Django 2.1.4 on 2019-01-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='linguatec_lexicon.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('src_language', models.CharField(max_length=16)),
                ('dst_language', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64, unique=True)),
                ('gramcat', models.CharField(choices=[('adj.', 'adjective'), ('adv.', 'adverb'), ('conj.', 'conjunction'), ('n.', 'noun'), ('v.', 'verb')], max_length=32)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='linguatec_lexicon.Lexicon')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='linguatec_lexicon.Word'),
        ),
    ]
