# Generated by Django 2.1.5 on 2019-01-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0002_create_gramcat_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='gramaticalcategory',
            options={'verbose_name_plural': 'gramatical categories'},
        ),
    ]
