# Generated by Django 2.1.5 on 2019-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0003_auto_word_entry_define_verbose_plural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='gramcat',
        ),
        migrations.AddField(
            model_name='entry',
            name='gramcats',
            field=models.ManyToManyField(related_name='entries', to='linguatec_lexicon.GramaticalCategory'),
        ),
    ]
