# Generated by Django 2.1.5 on 2019-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0004_0004_auto_multiple_gramcats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramaticalcategory',
            name='abbreviation',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
