# Generated by Django 2.1.5 on 2019-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0006_verbalconjugation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramaticalcategory',
            name='abbreviation',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
