# Generated by Django 2.1.5 on 2019-02-22 14:11

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0007_gramcat_abbr_to_64'),
    ]

    operations = [
        TrigramExtension(),
    ]
