# Generated by Django 2.1.5 on 2019-04-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0008_postres_trigram_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['pk'], 'verbose_name_plural': 'entries'},
        ),
    ]
