# Generated by Django 2.1.5 on 2019-07-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0010_diatopic_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['variation', 'pk'], 'verbose_name_plural': 'entries'},
        ),
    ]
