# Generated by Django 2.2.13 on 2020-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0012_lexicon_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicon',
            name='dst_language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='src_language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='lexicon',
            constraint=models.UniqueConstraint(fields=('src_language', 'dst_language'), name='src_language-dst_language'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('lexicon', 'term'), name='lexicon-term'),
        ),
    ]
