# Generated by Django 2.2.13 on 2020-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0013_auto_20201114_1202'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('word', 'variation', 'translation'), name='unique-entry'),
        ),
    ]
