# Generated by Django 2.2.24 on 2021-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0014_auto_20201216_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='marked_translation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
