# Generated by Django 3.1.7 on 2021-03-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0014_auto_20201216_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbalconjugation',
            name='raw_verbs',
            field=models.JSONField(default=list),
        ),
    ]
