# Generated by Django 2.2.13 on 2020-12-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0014_importsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ImportLog',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('running', 'RUNNING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], max_length=25),
        ),
    ]
