# Generated by Django 3.2.16 on 2022-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0015_entry_marked_translation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lexicon',
            name='src_language-dst_language',
        ),
        migrations.AddField(
            model_name='lexicon',
            name='topic',
            field=models.CharField(blank=True, help_text='The subject of the lexicon.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='lexicon',
            constraint=models.UniqueConstraint(fields=('src_language', 'dst_language', 'topic'), name='src-dst-topic'),
        ),
    ]
