# Generated by Django 4.1.3 on 2022-12-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0016_auto_lexicon_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('entries', models.ManyToManyField(related_name='labels', to='linguatec_lexicon.entry')),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='linguatec_lexicon.lexicon')),
            ],
        ),
    ]
