# Generated by Django 4.1.3 on 2023-03-24 10:43

from django.db import migrations, models
from linguatec_lexicon.models import annotate_words_slug


def generate_slug(apps, schema_editor):
    Lexicon = apps.get_model('linguatec_lexicon', 'Lexicon')

    lexicons = Lexicon.objects.all()
    for lexicon in lexicons:
        qs = annotate_words_slug(lexicon)
        qs.update(slug=models.F('calculated_slug'))


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0017_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(generate_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(),
        ),
    ]
