# Generated by Django 4.2.14 on 2024-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguatec_lexicon', '0018_word_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='etimol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
